services:
  frontend:
    image: santiagoarielv/sv-gestion-tarea
    ports:
      - "3000:80"
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
