services:
  frontend:
    image: santiagoarielv/sv-gestion-tarea
    ports:
      - "3000:3000"
    environment:
      - APP_API_URL=http://localhost:8080
    volumes:
      - .:/app                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
      - /app/node_modules
    depends_on:
      - backend
      - db
  backend:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
